2025-09-16 17:02:49	WARN	sdcal::calibrater::setvi(bool,bool)	Already using OLD VisibilityIterator.
2025-09-16 17:02:49	SEVERE	sdcal::::casa	Traceback (most recent call last):
2025-09-16 17:02:49	SEVERE	sdcal::::casa+	             ^^^^^^^^^^^^^^^^^^^^^
2025-09-16 17:02:49	SEVERE	sdcal::::casa+	  File "/scratch/scastro/casa/Tests/reports/casa-6.7.2-15-py3.12.el8/lib/py/lib/python3.12/site-packages/casatasks/private/task_sdcal.py", line 144, in sdcal
2025-09-16 17:02:49	SEVERE	sdcal::::casa+	    raise RuntimeError('Output file name must be specified.')
2025-09-16 17:02:49	SEVERE	sdcal::::casa+	RuntimeError: Output file name must be specified.
2025-09-16 17:02:49	SEVERE	sdcal::::casa	Output file name must be specified.
2025-09-16 17:02:49	SEVERE	sdcal::::casa	Task sdcal raised an exception of class RuntimeError with the following message: Output file name must be specified.
