{"name": "test_mesSet", "status": "failed", "statusDetails": {"message": "AssertionError: True is not false : delmod raises a severe error when run on a valid MS", "trace": "casatasks/test_task_delmod.py:89: in test_mesSet\n    self.assertFalse('SEVERE' in open('testlog.log').read(), msg='delmod raises a severe error when run on a valid MS')\nE   AssertionError: True is not false : delmod raises a severe error when run on a valid MS"}, "description": "\n            test_messet\n            -----------------\n            \n            Checks that only a valid MS is accept as input\n            \n            The first assert checks that no severe errors appear in the log when preforming the task on a valid MS\n            The second assert checks that a severe error is raised when the provided MS does not exist\n        ", "attachments": [{"name": "stdout", "source": "7941256a-17d4-425c-8f54-814e405f3128-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "32ef7a42-007b-4206-9027-7acd68b06d89-attachment.txt", "type": "text/plain"}], "start": 1758036882959, "stop": 1758036883278, "uuid": "b2dfda0f-3a22-4266-a1ae-6443485b795f", "historyId": "e18b93d39945c90edace40917148efb6", "testCaseId": "e18b93d39945c90edace40917148efb6", "fullName": "casatasks.test_task_delmod.delmod_test#test_mesSet", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_delmod"}, {"name": "subSuite", "value": "delmod_test"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_delmod"}], "titlePath": ["casatasks", "test_task_delmod.py", "delmod_test"]}