{"name": "test_image2ms_02", "status": "passed", "description": "02. failure case: execute image2ms with invalid datacolumn parameter, an exception raises.", "attachments": [{"name": "stderr", "source": "2cdfbaeb-dd57-411d-8380-a06aa37f5b84-attachment.txt", "type": "text/plain"}], "start": 1758038158631, "stop": 1758038158737, "uuid": "32e384d0-1f1e-4265-a961-5fe038a3a64e", "historyId": "6b8e93cf6c74f6b3c5ae4cf7f8184d3e", "testCaseId": "6b8e93cf6c74f6b3c5ae4cf7f8184d3e", "fullName": "casatasks.test_task_imbaseline.TestImage2MS#test_image2ms_02", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_imbaseline"}, {"name": "subSuite", "value": "TestImage2MS"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_imbaseline"}], "titlePath": ["casatasks", "test_task_imbaseline.py", "TestImage2MS"]}