{"name": "test_CAS_7620", "status": "failed", "statusDetails": {"message": "AssertionError: False is not true", "trace": "casatasks/test_task_specfit.py:94: in tearDown\n    self.assertTrue(len(self._tb.showcache()) == 0)\nE   AssertionError: False is not true"}, "description": "Test fix of segfault that occurred for small channel ranges", "attachments": [{"name": "stderr", "source": "dec6e1ff-b681-4c8f-843a-67db9751b488-attachment.txt", "type": "text/plain"}], "start": 1758043994501, "stop": 1758043994509, "uuid": "99e2e81e-e553-49bd-8054-ebe5427b2491", "historyId": "07304a690ab9a4019420c7bf6915d163", "testCaseId": "07304a690ab9a4019420c7bf6915d163", "fullName": "casatasks.test_task_specfit.specfit_test#test_CAS_7620", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_specfit"}, {"name": "subSuite", "value": "specfit_test"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_specfit"}], "titlePath": ["casatasks", "test_task_specfit.py", "specfit_test"]}