{"name": "test_badscan", "status": "passed", "description": "CAS-10054: Tests intermittent incorrect scan number in last row of single-scan dataset", "attachments": [{"name": "stdout", "source": "64763a6e-b467-4a10-8772-1ae175ca9ba8-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "d122e67e-c40f-4947-ba3c-1a147168f0c0-attachment.txt", "type": "text/plain"}], "start": 1758034682558, "stop": 1758034683023, "uuid": "5b18a88d-8f4a-40cc-8bb6-7e8125f7a7f6", "historyId": "3a98766c5fd056fcefb1a8aec2f1bf2a", "testCaseId": "3a98766c5fd056fcefb1a8aec2f1bf2a", "fullName": "casatools.test_tool_ms.mstool_test_fits#test_badscan", "labels": [{"name": "parentSuite", "value": "casatools"}, {"name": "suite", "value": "test_tool_ms"}, {"name": "subSuite", "value": "mstool_test_fits"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "593221-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatools.test_tool_ms"}], "titlePath": ["casatools", "test_tool_ms.py", "mstool_test_fits"]}