{"name": "test_bad_imagename", "status": "passed", "description": "Test bad image name throws exception", "start": 1758038894876, "stop": 1758038895637, "uuid": "2fbc8691-07a4-48ac-852f-a0cad244a35b", "historyId": "5c8538a6b61928c0df5a00520e98ac28", "testCaseId": "5c8538a6b61928c0df5a00520e98ac28", "fullName": "casatasks.test_task_imcontsub.imcontsub_test#test_bad_imagename", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_imcontsub"}, {"name": "subSuite", "value": "imcontsub_test"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_imcontsub"}], "titlePath": ["casatasks", "test_task_imcontsub.py", "imcontsub_test"]}