{"name": "test_reorderInvalid", "status": "passed", "description": "Test that invalid inputs for reorder raises exceptions", "attachments": [{"name": "stderr", "source": "c8291076-f1a1-42b2-9049-fe1bc1cfc377-attachment.txt", "type": "text/plain"}], "start": 1758034595906, "stop": 1758034595907, "uuid": "2d1d21d9-50bc-4840-9f9d-cd88cc3e6d99", "historyId": "30eda9eb41f5753d155f225236763946", "testCaseId": "30eda9eb41f5753d155f225236763946", "fullName": "casatools.test_tool_coordsys.coordsys_test#test_reorderInvalid", "labels": [{"name": "parentSuite", "value": "casatools"}, {"name": "suite", "value": "test_tool_coordsys"}, {"name": "subSuite", "value": "coordsys_test"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "593221-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatools.test_tool_coordsys"}], "titlePath": ["casatools", "test_tool_coordsys.py", "coordsys_test"]}