{"name": "test_setCalLib", "status": "passed", "description": " Check that a provided cal table can be used to corrupt the MODEL_DATA ", "attachments": [{"name": "stderr", "source": "6652257d-b7b9-42f0-8ff1-ab9e4584470a-attachment.txt", "type": "text/plain"}], "start": 1758034571555, "stop": 1758034575838, "uuid": "22f3c95d-8f52-4f76-aae9-88859a215ec2", "historyId": "6aac222b034202b754a6f733c0e85338", "testCaseId": "6aac222b034202b754a6f733c0e85338", "fullName": "casatools.test_tool_calibrater.calibrater_test#test_setCalLib", "labels": [{"name": "parentSuite", "value": "casatools"}, {"name": "suite", "value": "test_tool_calibrater"}, {"name": "subSuite", "value": "calibrater_test"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "593221-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatools.test_tool_calibrater"}], "titlePath": ["casatools", "test_tool_calibrater.py", "calibrater_test"]}