{"name": "test_filestack_15", "status": "passed", "description": "15. successful case: do erase() of _EraseableFolder contains a file.", "start": 1758038158018, "stop": 1758038158019, "uuid": "ba5c9afa-f660-426b-ba3a-80753304de01", "historyId": "b8c35d7acce830e875735499dcb222d3", "testCaseId": "b8c35d7acce830e875735499dcb222d3", "fullName": "casatasks.test_task_imbaseline.TestFileStack#test_filestack_15", "labels": [{"name": "parentSuite", "value": "casatasks"}, {"name": "suite", "value": "test_task_imbaseline"}, {"name": "subSuite", "value": "TestFileStack"}, {"name": "host", "value": "casa-rockylinux8-amd64-perf07"}, {"name": "thread", "value": "597558-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casatasks.test_task_imbaseline"}], "titlePath": ["casatasks", "test_task_imbaseline.py", "TestFileStack"]}